#application.yml

server:
  port: 8080

spring:
  datasource:
    jdbc-url: jdbc:mysql://59.225.206.13:3711/sc_fxyj?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Scfxyjpasswd741*
    driver-class-name: com.mysql.cj.jdbc.Driver
  second-datasource:
    jdbc-url: jdbc:mysql://59.225.206.13:3501/isgs-home?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: rewi
    password: Schlw+Rewis@201907
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
